spring:
    r2dbc:
        url: r2dbc:pool:postgresql://localhost:5432/blog
        username: blog
        password: blog
        pool:
            validation-query: SELECT 1
logging:
    level:
        org:
            springframework:
                data:
                    r2dbc: DEBUG