spring:
    r2dbc:
        url: r2dbc:pool:postgresql://localhost:5432/blog
        username: blog
        password: blog
        pool:
            validation-query: SELECT 1
    # JDBC Connection
#    datasource:
#        url: jdbc:postgresql://127.0.0.1:5432/blog
#        username: blog
#        password: blog
#        driverClassName: org.postgresql.Driver
#    jpa:
#        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
#        show-sql: true
#        properties:
#            hibernate:
#            dialect: org.hibernate.dialect.PostgreSQL9Dialect
#            hbm2ddl:
#                auto: update
#            temp:
#                use_jdbc_metadata_defaults: false
